create table public.estimate_projects (
  est_project_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  est_project_name text null,
  updated_at timestamp with time zone null default now(),
  team_id uuid null,
  street text null,
  city text null,
  state text null,
  zip text null,
  est_client_name text null,
  constraint estimate_projects_pkey primary key (est_project_id),
  constraint estimate_projects_team_id_fkey foreign KEY (team_id) references teams (team_id)
) TABLESPACE pg_default;

-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------

create table public.estimates (
  estimate_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  is_current boolean null default true,
  est_project_id bigint not null,
  version numeric not null default '1'::numeric,
  created_by uuid null,
  updated_by uuid null,
  updated_at timestamp with time zone null default now(),
  status text null default 'draft'::text,
  notes text null,
  tasks_order bigint[] null,
  default_cabinet_style_id bigint null,
  default_box_mat bigint null,
  default_face_mat bigint null,
  default_drawer_box_mat bigint null,
  default_hinge_id bigint null,
  default_slide_id bigint null,
  default_door_pull_id bigint null,
  default_drawer_pull_id bigint null,
  default_face_finish bigint[] null,
  default_box_finish bigint[] null,
  default_door_inside_molding boolean null,
  default_door_outside_molding boolean null,
  default_drawer_inside_molding boolean null,
  default_drawer_outside_molding boolean null,
  default_door_style text null,
  default_drawer_front_style text null,
  default_profit numeric null,
  default_commission numeric null,
  default_discount numeric null,
  line_items jsonb null default '[]'::jsonb,
  default_service_price_overrides jsonb null,
  parts_included jsonb null,
  services_included jsonb null,
  default_door_panel_mod_id bigint null,
  default_drawer_panel_mod_id bigint null,
  custom_notes jsonb null,
  finalized_on timestamp with time zone null,
  price_overrides jsonb null default '{}'::jsonb,
  archived_at timestamp with time zone null,
  default_horizontal_grain boolean null,
  default_include_door_pulls boolean null,
  default_include_drawer_pulls boolean null,
  constraint estimates_pkey primary key (estimate_id),
  constraint estimates_id_key unique (estimate_id),
  constraint estimates_default_cabinet_style_id_fkey foreign KEY (default_cabinet_style_id) references cabinet_styles (id) on update CASCADE,
  constraint estimates_default_door_pull_id_fkey foreign KEY (default_door_pull_id) references hardware_pulls (id) on update CASCADE,
  constraint estimates_default_drawer_box_mat_fkey foreign KEY (default_drawer_box_mat) references drawer_wood_catalog (id) on update CASCADE,
  constraint estimates_default_drawer_pull_id_fkey foreign KEY (default_drawer_pull_id) references hardware_pulls (id) on update CASCADE,
  constraint estimates_default_face_mat_fkey foreign KEY (default_face_mat) references wood_catalog (id) on update CASCADE,
  constraint estimates_default_hinge_id_fkey foreign KEY (default_hinge_id) references hardware_hinges (id) on update CASCADE,
  constraint estimates_default_slide_id_fkey foreign KEY (default_slide_id) references hardware_slides (id) on update CASCADE,
  constraint estimates_est_project_id_fkey foreign KEY (est_project_id) references estimate_projects (est_project_id) on update CASCADE on delete CASCADE,
  constraint estimates_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint estimates_updated_by_fkey foreign KEY (updated_by) references auth.users (id),
  constraint estimates_default_box_mat_fkey foreign KEY (default_box_mat) references wood_catalog (id) on update CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_estimates_archived_at on public.estimates using btree (archived_at) TABLESPACE pg_default;

create trigger trg_update_project_on_estimate_change
after INSERT
or
update on estimates for EACH row
execute FUNCTION update_project_timestamp_from_estimates ();

-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------

create table public.estimate_tasks (
  est_task_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  est_task_name text null,
  updated_at timestamp with time zone null default now(),
  estimate_id bigint null,
  sections_order bigint[] null default '{}'::bigint[],
  quantity numeric null,
  constraint estimate_tasks_pkey primary key (est_task_id),
  constraint estimate_tasks_estimate_id_fkey foreign KEY (estimate_id) references estimates (estimate_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create trigger create_initial_section_trigger
after INSERT on estimate_tasks for EACH row
execute FUNCTION create_initial_section ();

create trigger trg_update_estimate_on_task_change
after INSERT
or DELETE
or
update on estimate_tasks for EACH row
execute FUNCTION update_estimate_timestamp_from_tasks ();

-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------

create table public.estimate_sections (
  est_section_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  est_task_id bigint null,
  box_mat bigint null,
  face_mat bigint null,
  cabinets_order bigint[] null default '{}'::bigint[],
  accessories_order bigint[] null default '{}'::bigint[],
  lengths_order bigint[] null default '{}'::bigint[],
  other_order bigint[] null default '{}'::bigint[],
  cabinet_style_id bigint null,
  drawer_box_mat bigint null,
  hinge_id bigint null,
  slide_id bigint null,
  door_pull_id bigint null,
  drawer_pull_id bigint null,
  face_finish bigint[] null,
  box_finish bigint[] null,
  quantity numeric not null default '1'::numeric,
  profit numeric null,
  commission numeric null,
  discount numeric null,
  door_inside_molding boolean null,
  door_outside_molding boolean null,
  drawer_inside_molding boolean null,
  drawer_outside_molding boolean null,
  notes jsonb null,
  door_style text null,
  drawer_front_style text null,
  add_hours jsonb null default '{"finish_setup_hours": 1, "install_setup_hours": 1}'::jsonb,
  section_name text null,
  service_price_overrides jsonb null,
  parts_included jsonb null,
  services_included jsonb null,
  door_panel_mod_id bigint null,
  drawer_panel_mod_id bigint null,
  door_mat bigint null,
  door_finish bigint[] null,
  drawer_front_mat bigint null,
  drawer_front_finish bigint[] null,
  use_default_prices boolean null default false,
  scheduled_task_id bigint null,
  horizontal_grain boolean null,
  include_door_pulls boolean null,
  include_drawer_pulls boolean null,
  constraint estimate_sections_pkey primary key (est_section_id),
  constraint estimate_sections_cabinet_style_id_fkey foreign KEY (cabinet_style_id) references cabinet_styles (id) on update CASCADE,
  constraint estimate_sections_door_mat_fkey foreign KEY (door_mat) references wood_catalog (id) on update CASCADE,
  constraint estimate_sections_door_pull_id_fkey foreign KEY (door_pull_id) references hardware_pulls (id),
  constraint estimate_sections_drawer_box_mat_fkey foreign KEY (drawer_box_mat) references drawer_wood_catalog (id) on update CASCADE,
  constraint estimate_sections_drawer_front_mat_fkey foreign KEY (drawer_front_mat) references wood_catalog (id) on update CASCADE,
  constraint estimate_sections_drawer_pull_id_fkey foreign KEY (drawer_pull_id) references hardware_pulls (id) on update CASCADE,
  constraint estimate_sections_est_task_id_fkey foreign KEY (est_task_id) references estimate_tasks (est_task_id) on update CASCADE on delete CASCADE,
  constraint estimate_sections_face_mat_fkey foreign KEY (face_mat) references wood_catalog (id),
  constraint estimate_sections_hinge_id_fkey foreign KEY (hinge_id) references hardware_hinges (id),
  constraint estimate_sections_scheduled_task_id_fkey foreign KEY (scheduled_task_id) references tasks (task_id) on delete set null,
  constraint estimate_sections_slide_id_fkey foreign KEY (slide_id) references hardware_slides (id),
  constraint estimate_sections_box_mat_fkey foreign KEY (box_mat) references wood_catalog (id),
  constraint quantity_non_negative check ((quantity >= (0)::numeric))
) TABLESPACE pg_default;

create trigger add_section_to_task_order_trigger
after INSERT on estimate_sections for EACH row
execute FUNCTION add_section_to_task_order ();

create trigger remove_section_from_task_order_trigger
after DELETE on estimate_sections for EACH row
execute FUNCTION remove_section_from_task_order ();

create trigger trg_update_estimate_on_section_change
after INSERT
or DELETE
or
update on estimate_sections for EACH row
execute FUNCTION update_estimate_timestamp_from_sections ();

-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------

create table public.estimate_cabinets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  updated_at timestamp with time zone null default now(),
  est_section_id bigint null,
  width numeric null,
  height numeric null,
  depth numeric null,
  quantity bigint null default '1'::bigint,
  temp_id uuid null,
  face_config jsonb null,
  finished_interior boolean null default false,
  type bigint not null,
  cabinet_style_override bigint null,
  finished_left boolean null,
  finished_right boolean null,
  saved_style_id bigint null,
  finished_top boolean null,
  finished_bottom boolean null,
  finished_back boolean null,
  type_specific_options jsonb null default '{}'::jsonb,
  fin_back_mat bigint null,
  fin_back_finish bigint[] null,
  fin_back_panel_mod bigint null,
  constraint estimate_cabinets_pkey primary key (id),
  constraint estimate_cabinets_id_key unique (id),
  constraint estimate_cabinets_cabinet_style_override_fkey foreign KEY (cabinet_style_override) references cabinet_styles (id) on update CASCADE,
  constraint estimate_cabinets_est_section_id_fkey foreign KEY (est_section_id) references estimate_sections (est_section_id) on update CASCADE on delete CASCADE,
  constraint estimate_cabinets_saved_style_id_fkey foreign KEY (saved_style_id) references cabinet_styles (id) on update CASCADE,
  constraint estimate_cabinets_type_fkey foreign KEY (type) references cabinet_types (id)
) TABLESPACE pg_default;

create trigger trg_update_estimate_on_cabinet_change
after INSERT
or DELETE
or
update on estimate_cabinets for EACH row
execute FUNCTION update_estimate_timestamp_from_cabinets ();

create trigger update_cabinets_order
after INSERT
or DELETE on estimate_cabinets for EACH row
execute FUNCTION update_section_order ();

-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------

create table public.estimate_accessories (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  est_section_id bigint null,
  quantity numeric(10, 4) null default '1'::bigint,
  temp_id uuid null,
  accessory_catalog_id bigint null,
  est_cabinet_id bigint null,
  face_id text null,
  width numeric(10, 4) null,
  height numeric(10, 4) null,
  depth numeric(10, 4) null,
  hardware_pull_id bigint null,
  hardware_hinge_id bigint null,
  hardware_slide_id bigint null,
  constraint estimate_accessories_pkey primary key (id),
  constraint estimate_accessories_id_key unique (id),
  constraint estimate_accessories_est_section_id_fkey foreign KEY (est_section_id) references estimate_sections (est_section_id) on update CASCADE on delete CASCADE,
  constraint estimate_accessories_hardware_hinge_id_fkey foreign KEY (hardware_hinge_id) references hardware_hinges (id) on delete set null,
  constraint estimate_accessories_accessory_catalog_id_fkey foreign KEY (accessory_catalog_id) references accessories_catalog (id) on delete set null,
  constraint estimate_accessories_hardware_slide_id_fkey foreign KEY (hardware_slide_id) references hardware_slides (id) on delete set null,
  constraint estimate_accessories_hardware_pull_id_fkey foreign KEY (hardware_pull_id) references hardware_pulls (id) on delete set null,
  constraint estimate_accessories_est_cabinet_id_fkey foreign KEY (est_cabinet_id) references estimate_cabinets (id) on delete CASCADE,
  constraint estimate_accessories_one_item_ref_chk check (
    (
      num_nonnulls (
        accessory_catalog_id,
        hardware_pull_id,
        hardware_hinge_id,
        hardware_slide_id
      ) = 1
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_estimate_accessories_catalog on public.estimate_accessories using btree (accessory_catalog_id) TABLESPACE pg_default;

create index IF not exists idx_estimate_accessories_cabinet on public.estimate_accessories using btree (est_cabinet_id) TABLESPACE pg_default;

create trigger trg_update_estimate_on_accessory_change
after INSERT
or DELETE
or
update on estimate_accessories for EACH row
execute FUNCTION update_estimate_timestamp_from_accessories ();

create trigger update_accessories_order
after INSERT
or DELETE on estimate_accessories for EACH row
execute FUNCTION update_section_order ();

-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------

create table public.estimate_lengths (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  updated_at timestamp with time zone null default now(),
  est_section_id bigint null,
  length numeric null,
  quantity bigint null default '1'::bigint,
  temp_id uuid null,
  length_catalog_id bigint null,
  miter_count integer null default 0,
  width numeric(10, 4) null,
  thickness numeric(10, 4) null,
  cutout_count numeric not null default '0'::numeric,
  length_mat bigint null,
  length_finish bigint[] null,
  constraint estimate_lengths_pkey primary key (id),
  constraint estimate_lengths_id_key unique (id),
  constraint estimate_lengths_est_section_id_fkey foreign KEY (est_section_id) references estimate_sections (est_section_id) on update CASCADE on delete CASCADE,
  constraint estimate_lengths_length_catalog_id_fkey foreign KEY (length_catalog_id) references lengths_catalog (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create trigger trg_update_estimate_on_length_change
after INSERT
or DELETE
or
update on estimate_lengths for EACH row
execute FUNCTION update_estimate_timestamp_from_lengths ();

create trigger update_lengths_order
after INSERT
or DELETE on estimate_lengths for EACH row
execute FUNCTION update_section_order ();

-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------

create table public.estimate_other (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  updated_at timestamp with time zone null default now(),
  est_section_id bigint null,
  width numeric null,
  height numeric null,
  depth numeric null,
  quantity bigint null default '1'::bigint,
  temp_id uuid null,
  price numeric null,
  note_included boolean not null default false,
  constraint estimate_other_pkey primary key (id),
  constraint estimate_other_id_key unique (id),
  constraint estimate_other_est_section_id_fkey foreign KEY (est_section_id) references estimate_sections (est_section_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create trigger trg_update_estimate_on_other_change
after INSERT
or DELETE
or
update on estimate_other for EACH row
execute FUNCTION update_estimate_timestamp_from_other ();

create trigger update_other_order
after INSERT
or DELETE on estimate_other for EACH row
execute FUNCTION update_section_order ();

-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------



-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------



-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------



-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------



-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------