create table public.projects (
  project_id bigint generated by default as identity not null,
  project_created_at timestamp with time zone not null default now(),
  project_name text not null,
  project_completed_at timestamp with time zone null,
  needs_attention boolean null default false,
  deposit_date timestamp with time zone null,
  team_id uuid null,
  delivery_date timestamp with time zone null,
  delivery_date_updated_at timestamp with time zone null,
  project_notes text null,
  project_scheduled_at timestamp with time zone null default now(),
  constraint projects_pkey primary key (project_id),
  constraint projects_id_key unique (project_id),
  constraint projects_team_id_fkey foreign KEY (team_id) references teams (team_id)
) TABLESPACE pg_default;

create trigger on_delivery_date_change BEFORE INSERT
or
update on projects for EACH row
execute FUNCTION handle_delivery_date_updated ();

create table public.tasks (
  task_id bigint generated by default as identity not null,
  project_id bigint not null,
  task_number text not null,
  task_name text not null,
  task_active boolean not null default true,
  task_created_at timestamp with time zone not null default now(),
  temp_task_id uuid null,
  est_duration numeric null,
  task_completed_at timestamp with time zone null,
  estimate_snapshot jsonb null,
  constraint tasks_pkey primary key (task_id),
  constraint tasks_task_id_key unique (task_id),
  constraint tasks_project_id_fkey foreign KEY (project_id) references projects (project_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.subtasks (
  subtask_id bigint generated by default as identity not null,
  task_id bigint not null,
  employee_id bigint not null,
  subtask_created_at timestamp with time zone not null default now(),
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  duration numeric not null,
  subtask_width integer not null,
  temp_subtask_id uuid null,
  hard_start_date boolean null default false,
  constraint subtasks_pkey primary key (subtask_id),
  constraint subtasks_subtask_id_key unique (subtask_id),
  constraint subtasks_employee_id_fkey foreign KEY (employee_id) references employees (employee_id) on delete set default,
  constraint subtasks_task_id_fkey foreign KEY (task_id) references tasks (task_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create view public.task_full_details
with
  (security_invoker = true) as
select
  et.est_task_id,
  et.created_at,
  et.est_task_name,
  et.updated_at,
  et.estimate_id,
  et.sections_order,
  et.quantity,
  (
    select
      json_agg(
        jsonb_set(
          jsonb_set(
            jsonb_set(
              jsonb_set(
                to_jsonb(es.*),
                '{cabinets}'::text[],
                (
                  select
                    COALESCE(
                      json_agg(
                        to_jsonb(ec.*)
                        order by
                          (
                            COALESCE(array_position(es.cabinets_order, ec.id), 99999)
                          ),
                          ec.id
                      ),
                      '[]'::json
                    )::jsonb as "coalesce"
                  from
                    estimate_cabinets ec
                  where
                    ec.est_section_id = es.est_section_id
                )
              ),
              '{lengths}'::text[],
              (
                select
                  COALESCE(
                    json_agg(
                      to_jsonb(el.*)
                      order by
                        (
                          COALESCE(array_position(es.lengths_order, el.id), 99999)
                        ),
                        el.id
                    ),
                    '[]'::json
                  )::jsonb as "coalesce"
                from
                  estimate_lengths el
                where
                  el.est_section_id = es.est_section_id
              )
            ),
            '{accessories}'::text[],
            (
              select
                COALESCE(
                  json_agg(
                    to_jsonb(ea.*)
                    order by
                      (
                        COALESCE(
                          array_position(es.accessories_order, ea.id),
                          99999
                        )
                      ),
                      ea.id
                  ),
                  '[]'::json
                )::jsonb as "coalesce"
              from
                estimate_accessories ea
              where
                ea.est_section_id = es.est_section_id
            )
          ),
          '{other}'::text[],
          (
            select
              COALESCE(
                json_agg(
                  to_jsonb(eo.*)
                  order by
                    (
                      COALESCE(array_position(es.other_order, eo.id), 99999)
                    ),
                    eo.id
                ),
                '[]'::json
              )::jsonb as "coalesce"
            from
              estimate_other eo
            where
              eo.est_section_id = es.est_section_id
          )
        )
        order by
          (
            COALESCE(
              array_position(et.sections_order, es.est_section_id),
              99999
            )
          ),
          es.est_section_id
      ) as json_agg
    from
      estimate_sections es
    where
      es.est_task_id = et.est_task_id
      and (es.est_section_id = any (et.sections_order))
  ) as sections
from
  estimate_tasks et;