-- Create length_catalog_rules table
-- Rules are composable fabrication behaviors attached to length catalog items.
-- Each rule has a key (e.g. 'nosing', 'cleating') and a params JSONB for config.
-- The calculation engine iterates rules in sort_order and merges results.

create table public.length_catalog_rules (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  length_catalog_id bigint not null,
  rule_key text not null,
  params jsonb not null default '{}',
  sort_order int not null default 0,
  constraint length_catalog_rules_pkey primary key (id),
  constraint length_catalog_rules_catalog_fkey
    foreign key (length_catalog_id) references lengths_catalog (id)
    on update cascade on delete cascade,
  constraint length_catalog_rules_unique unique (length_catalog_id, rule_key)
) tablespace pg_default;

-- RLS:
-- - All team members can select length rules for their team.
-- - Only users with team permission "can_manage_teams" can insert/update/delete
--   (role_id=1 admins are allowed by has_team_permission baseline).
alter table public.length_catalog_rules enable row level security;

create policy "Team members can view their length rules"
  on public.length_catalog_rules for select
  using (
    exists (
      select 1
      from public.lengths_catalog lc
      join public.team_members tm on tm.team_id = lc.team_id
      where lc.id = length_catalog_rules.length_catalog_id
        and tm.user_id = auth.uid()
    )
  );

create policy "Team members can insert length rules"
  on public.length_catalog_rules for insert
  with check (
    public.has_team_permission(
      (
        select lc.team_id
        from public.lengths_catalog lc
        where lc.id = length_catalog_rules.length_catalog_id
      ),
      'can_manage_teams'
    )
  );

create policy "Team members can update length rules"
  on public.length_catalog_rules for update
  using (
    public.has_team_permission(
      (
        select lc.team_id
        from public.lengths_catalog lc
        where lc.id = length_catalog_rules.length_catalog_id
      ),
      'can_manage_teams'
    )
  )
  with check (
    public.has_team_permission(
      (
        select lc.team_id
        from public.lengths_catalog lc
        where lc.id = length_catalog_rules.length_catalog_id
      ),
      'can_manage_teams'
    )
  );

create policy "Team members can delete length rules"
  on public.length_catalog_rules for delete
  using (
    public.has_team_permission(
      (
        select lc.team_id
        from public.lengths_catalog lc
        where lc.id = length_catalog_rules.length_catalog_id
      ),
      'can_manage_teams'
    )
  );

-- Comments for documentation
comment on table public.length_catalog_rules is 'Composable fabrication rules attached to length catalog items. Each rule adds material and/or labor effects during calculation.';
comment on column public.length_catalog_rules.rule_key is 'Rule identifier: nosing, cleating, seam_if_long, full_depth_return';
comment on column public.length_catalog_rules.params is 'Rule-specific configuration (thresholds, multipliers, service IDs). Structure varies by rule_key.';
comment on column public.length_catalog_rules.sort_order is 'Execution order for rules on the same catalog item. Lower = earlier.';
