-- Create lengths_catalog table (team-specific length types)
create table public.lengths_catalog (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  team_id uuid not null,
  name text not null,
  type text not null, -- 'molding', 'base', 'shelf', 'top', etc.
  requires_miters boolean not null default false,
  requires_cutouts boolean not null default false,
  default_width numeric(10, 4) null, -- Default width in inches for this type (e.g., crown is typically 3.5")
  default_thickness numeric(10, 4) null, -- Default thickness in inches (e.g., 0.75" for most molding)
  description text null,
  constraint lengths_catalog_pkey primary key (id),
  constraint lengths_catalog_id_key unique (id),
  constraint lengths_catalog_team_id_fkey foreign key (team_id) references teams (team_id) on update cascade on delete cascade
) tablespace pg_default;

-- Create index on team_id for efficient lookups
-- create index lengths_catalog_team_id_idx on public.lengths_catalog using btree (team_id);

-- Create length_services table (separate from hardware_services)
create table public.length_services (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  length_catalog_id bigint not null,
  team_service_id bigint not null,
  time_per_unit numeric(10, 4) not null default 0,
  is_miter_time boolean not null default false, -- true = miter time, false = regular time per foot
  is_cutout_time boolean not null default false, -- true = cutout time, false = regular time per foot
  constraint length_services_pkey primary key (id),
  constraint length_services_id_key unique (id),
  constraint length_services_length_catalog_id_fkey foreign key (length_catalog_id) references lengths_catalog (id) on update cascade on delete cascade,
  constraint length_services_team_service_id_fkey foreign key (team_service_id) references team_services (id) on update cascade on delete cascade,
  constraint length_services_unique unique (length_catalog_id, team_service_id, is_miter_time, is_cutout_time)
) tablespace pg_default;

-- Create indexes for efficient lookups
-- create index length_services_length_catalog_id_idx on public.length_services using btree (length_catalog_id);
-- create index length_services_team_service_id_idx on public.length_services using btree (team_service_id);

-- Update estimate_lengths table to reference catalog
alter table public.estimate_lengths
  add column if not exists length_catalog_id bigint null,
  add column if not exists miter_count integer null default 0,
  add column if not exists cutout_count integer null default 0,
  add column if not exists width numeric(10, 4) null, -- Width in inches (can override catalog default)
  add column if not exists thickness numeric(10, 4) null, -- Thickness in inches (can override catalog default)
  add constraint estimate_lengths_length_catalog_id_fkey 
    foreign key (length_catalog_id) 
    references lengths_catalog (id) 
    on update cascade 
    on delete set null;

-- -- Create index on length_catalog_id
-- create index if not exists estimate_lengths_length_catalog_id_idx 
--   on public.estimate_lengths using btree (length_catalog_id);

-- Add comments for documentation
comment on table public.lengths_catalog is 'Team-specific catalog of length types (crown, toe kick, etc.) with default dimensions';
comment on table public.length_services is 'Time per unit for each length catalog item per service (includes regular time per foot, miter time, and cutout time)';
comment on column public.length_services.is_miter_time is 'false = time per foot for regular length, true = time per miter cut';
comment on column public.length_services.is_cutout_time is 'false = time per foot for regular length, true = time per cutout';
comment on column public.estimate_lengths.length_catalog_id is 'Reference to the catalog item this length is based on (nullable for custom lengths)';
comment on column public.estimate_lengths.miter_count is 'Number of miters for this length item';
comment on column public.estimate_lengths.cutout_count is 'Number of cutouts for this length item';
comment on column public.estimate_lengths.width is 'Width in inches (defaults to catalog default_width if not specified)';
comment on column public.estimate_lengths.thickness is 'Thickness in inches (defaults to catalog default_thickness if not specified)';
