-- Refactor length_services: consolidate boolean flags into nullable numeric columns.
-- Old: multiple rows per (length_catalog_id, team_service_id) distinguished by is_miter_time/is_cutout_time
-- New: one row per (length_catalog_id, team_service_id) with time_per_unit, miter_minutes, cutout_minutes, base_minutes
--
-- This is a destructive migration — existing length_services data will be lost.
-- Acceptable since lengths feature is in early stages.

-- 1. Drop the old table (cascade removes RLS policies, indexes, etc.)
DROP TABLE IF EXISTS public.length_services CASCADE;

-- 2. Recreate with new schema
CREATE TABLE public.length_services (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  length_catalog_id bigint not null,
  team_service_id bigint not null,
  time_per_unit numeric(10, 4) null,      -- minutes per linear foot
  miter_minutes numeric(10, 4) null,      -- minutes per miter
  cutout_minutes numeric(10, 4) null,     -- minutes per cutout
  base_minutes numeric(10, 4) null,        -- minimum minutes per service per length item
  constraint length_services_pkey primary key (id),
  constraint length_services_unique unique (length_catalog_id, team_service_id),
  constraint length_services_length_catalog_id_fkey foreign key (length_catalog_id)
    references lengths_catalog (id) on update cascade on delete cascade,
  constraint length_services_team_service_id_fkey foreign key (team_service_id)
    references team_services (id) on update cascade on delete cascade
) tablespace pg_default;

comment on table public.length_services is 'Per-service labor config for each length catalog item. One row per (catalog item, service).';
comment on column public.length_services.time_per_unit is 'Minutes per linear foot for this service';
comment on column public.length_services.miter_minutes is 'Minutes per miter cut for this service (null = no miter labor)';
comment on column public.length_services.cutout_minutes is 'Minutes per cutout for this service (null = no cutout labor)';
comment on column public.length_services.base_minutes is 'Minimum minutes charged for this service regardless of length (null = no minimum)';

-- 3. Re-add RLS using has_team_permission for can_manage_teams
-- - All team members can select length services for their team.
-- - Only users with team permission "can_manage_teams" can insert/update/delete
--   (role_id=1 admins are allowed by has_team_permission baseline).
ALTER TABLE public.length_services ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Team members can view their length services"
  ON public.length_services FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.lengths_catalog lc
      JOIN public.team_members tm ON tm.team_id = lc.team_id
      WHERE lc.id = length_services.length_catalog_id
        AND tm.user_id = auth.uid()
    )
  );

CREATE POLICY "Team members can insert length services"
  ON public.length_services FOR INSERT
  WITH CHECK (
    public.has_team_permission(
      (
        SELECT lc.team_id
        FROM public.lengths_catalog lc
        WHERE lc.id = length_services.length_catalog_id
      ),
      'can_manage_teams'
    )
  );

CREATE POLICY "Team members can update length services"
  ON public.length_services FOR UPDATE
  USING (
    public.has_team_permission(
      (
        SELECT lc.team_id
        FROM public.lengths_catalog lc
        WHERE lc.id = length_services.length_catalog_id
      ),
      'can_manage_teams'
    )
  )
  WITH CHECK (
    public.has_team_permission(
      (
        SELECT lc.team_id
        FROM public.lengths_catalog lc
        WHERE lc.id = length_services.length_catalog_id
      ),
      'can_manage_teams'
    )
  );

CREATE POLICY "Team members can delete length services"
  ON public.length_services FOR DELETE
  USING (
    public.has_team_permission(
      (
        SELECT lc.team_id
        FROM public.lengths_catalog lc
        WHERE lc.id = length_services.length_catalog_id
      ),
      'can_manage_teams'
    )
  );

-- 4. Replace save_length_settings RPC to match new schema
CREATE OR REPLACE FUNCTION save_length_settings(
  p_items JSONB DEFAULT '[]'::JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_team_id UUID;
  v_item JSONB;
  v_service JSONB;
  v_rule JSONB;
  v_catalog_id BIGINT;
  v_team_service_id BIGINT;
  v_existing_id BIGINT;
  v_time_per_unit NUMERIC;
  v_miter_minutes NUMERIC;
  v_cutout_minutes NUMERIC;
  v_base_minutes NUMERIC;
  v_rule_key TEXT;
  v_items_processed INT := 0;
  v_has_any_value BOOLEAN;
BEGIN
  -- Resolve team from current user
  SELECT tm.team_id
  INTO v_team_id
  FROM team_members tm
  WHERE tm.user_id = auth.uid()
  LIMIT 1;

  IF v_team_id IS NULL THEN
    RAISE EXCEPTION 'No team found for current user';
  END IF;

  -- Process each catalog item
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_catalog_id := (v_item ->> 'length_catalog_id')::BIGINT;

    -- Verify this catalog item belongs to the user's team
    IF NOT EXISTS (
      SELECT 1 FROM lengths_catalog
      WHERE id = v_catalog_id AND team_id = v_team_id
    ) THEN
      RAISE EXCEPTION 'Catalog item % does not belong to team', v_catalog_id;
    END IF;

    -- ══════════════════════════════════════
    -- SERVICES: one row per (length_catalog_id, team_service_id)
    -- ══════════════════════════════════════
    IF v_item ? 'services' THEN
      FOR v_service IN SELECT * FROM jsonb_array_elements(v_item -> 'services')
      LOOP
        -- Parse nullable numeric fields: JSON null or missing → SQL NULL
        v_time_per_unit := CASE
          WHEN v_service ->> 'time_per_unit' IS NULL OR v_service ->> 'time_per_unit' = '' THEN NULL
          ELSE (v_service ->> 'time_per_unit')::NUMERIC
        END;
        v_miter_minutes := CASE
          WHEN v_service ->> 'miter_minutes' IS NULL OR v_service ->> 'miter_minutes' = '' THEN NULL
          ELSE (v_service ->> 'miter_minutes')::NUMERIC
        END;
        v_cutout_minutes := CASE
          WHEN v_service ->> 'cutout_minutes' IS NULL OR v_service ->> 'cutout_minutes' = '' THEN NULL
          ELSE (v_service ->> 'cutout_minutes')::NUMERIC
        END;
        v_base_minutes := CASE
          WHEN v_service ->> 'base_minutes' IS NULL OR v_service ->> 'base_minutes' = '' THEN NULL
          ELSE (v_service ->> 'base_minutes')::NUMERIC
        END;

        -- Resolve service_id -> team_service_id
        SELECT ts.id INTO v_team_service_id
        FROM team_services ts
        WHERE ts.team_id = v_team_id
          AND ts.service_id = (v_service ->> 'service_id')::BIGINT
        LIMIT 1;

        IF v_team_service_id IS NULL THEN
          CONTINUE;
        END IF;

        -- Check if any value is non-null (skip entirely empty rows)
        v_has_any_value := COALESCE(v_time_per_unit, v_miter_minutes, v_cutout_minutes, v_base_minutes) IS NOT NULL;

        -- Check if this service row already exists
        SELECT ls.id INTO v_existing_id
        FROM length_services ls
        WHERE ls.length_catalog_id = v_catalog_id
          AND ls.team_service_id = v_team_service_id;

        IF v_existing_id IS NOT NULL THEN
          IF NOT v_has_any_value THEN
            -- All values null → delete the row
            DELETE FROM length_services WHERE id = v_existing_id;
          ELSE
            -- Update if changed
            UPDATE length_services
            SET time_per_unit = v_time_per_unit,
                miter_minutes = v_miter_minutes,
                cutout_minutes = v_cutout_minutes,
                base_minutes = v_base_minutes,
                updated_at = now()
            WHERE id = v_existing_id
              AND (
                time_per_unit IS DISTINCT FROM v_time_per_unit
                OR miter_minutes IS DISTINCT FROM v_miter_minutes
                OR cutout_minutes IS DISTINCT FROM v_cutout_minutes
                OR base_minutes IS DISTINCT FROM v_base_minutes
              );
          END IF;
        ELSE
          -- New row → insert only if at least one value is non-null
          IF v_has_any_value THEN
            INSERT INTO length_services (
              length_catalog_id, team_service_id,
              time_per_unit, miter_minutes, cutout_minutes, base_minutes
            ) VALUES (
              v_catalog_id, v_team_service_id,
              v_time_per_unit, v_miter_minutes, v_cutout_minutes, v_base_minutes
            );
          END IF;
        END IF;
      END LOOP;
    END IF;

    -- ══════════════════════════════════════
    -- RULES: targeted update / insert / delete (unchanged)
    -- ══════════════════════════════════════
    IF v_item ? 'rules' THEN
      -- Delete rules no longer in the desired set
      DELETE FROM length_catalog_rules
      WHERE length_catalog_id = v_catalog_id
        AND rule_key NOT IN (
          SELECT r ->> 'rule_key'
          FROM jsonb_array_elements(v_item -> 'rules') AS r
        );

      -- Update or insert desired rules
      FOR v_rule IN SELECT * FROM jsonb_array_elements(v_item -> 'rules')
      LOOP
        v_rule_key := v_rule ->> 'rule_key';

        SELECT lcr.id INTO v_existing_id
        FROM length_catalog_rules lcr
        WHERE lcr.length_catalog_id = v_catalog_id
          AND lcr.rule_key = v_rule_key;

        IF v_existing_id IS NOT NULL THEN
          UPDATE length_catalog_rules
          SET params = COALESCE(v_rule -> 'params', '{}'::JSONB),
              sort_order = COALESCE((v_rule ->> 'sort_order')::INT, 0),
              updated_at = now()
          WHERE id = v_existing_id
            AND (
              params IS DISTINCT FROM COALESCE(v_rule -> 'params', '{}'::JSONB)
              OR sort_order IS DISTINCT FROM COALESCE((v_rule ->> 'sort_order')::INT, 0)
            );
        ELSE
          INSERT INTO length_catalog_rules (
            length_catalog_id, rule_key, params, sort_order
          ) VALUES (
            v_catalog_id,
            v_rule_key,
            COALESCE(v_rule -> 'params', '{}'::JSONB),
            COALESCE((v_rule ->> 'sort_order')::INT, 0)
          );
        END IF;
      END LOOP;
    END IF;

    v_items_processed := v_items_processed + 1;
  END LOOP;

  RETURN jsonb_build_object(
    'success', TRUE,
    'items_processed', v_items_processed
  );
END;
$$;

GRANT EXECUTE ON FUNCTION save_length_settings(JSONB) TO authenticated;
