import PropTypes from "prop-types";
import { useEffect, useMemo, useState } from "react";
import { FiEdit2, FiSave, FiX } from "react-icons/fi";
import { useSelector } from "react-redux";

import { createSectionContext } from "../../utils/createSectionContext";
import { getSectionCalculations } from "../../utils/getSectionCalculations";
import {
  buildAdditionalSectionNotesText,
  getOptionsForNoteIndex,
} from "../../utils/sectionNotesHelpers";

const buildDefaultOptions = (noteIndex) => {
  const opts = {};

  getOptionsForNoteIndex(noteIndex).forEach((opt) => {
    if (opt.type === "text-boolean") {
      opts[opt.key] = [false, ""];
    } else {
      opts[opt.key] = false;
    }
  });

  return opts;
};

const createDefaultNoteEntry = (index) => ({
  note: "",
  options: buildDefaultOptions(index),
});

const createEmptyNotes = () =>
  [0, 1, 2].map((index) => createDefaultNoteEntry(index));

const normalizeOptionValue = (opt, raw) => {
  if (opt.type === "text-boolean") {
    if (typeof raw === "string") {
      return [true, raw];
    }

    if (Array.isArray(raw)) {
      return [Boolean(raw[0]), typeof raw[1] === "string" ? raw[1] : ""];
    }

    return [false, ""];
  }

  return Boolean(raw);
};

const normalizeOptions = (options, noteIndex) => {
  const raw =
    options && typeof options === "object" && !Array.isArray(options)
      ? options
      : {};
  const normalized = {};

  getOptionsForNoteIndex(noteIndex).forEach((opt) => {
    normalized[opt.key] = normalizeOptionValue(opt, raw[opt.key]);
  });

  return normalized;
};

const normalizeNoteEntry = (entry, index) => {
  if (!entry || typeof entry !== "object" || Array.isArray(entry)) {
    return createDefaultNoteEntry(index);
  }

  return {
    note: typeof entry.note === "string" ? entry.note : "",
    options: normalizeOptions(entry.options, index),
  };
};

const normalizeNotes = (notes) => {
  if (Array.isArray(notes)) {
    return [0, 1, 2].map((index) => {
      const noteEntry = notes[index];

      if (typeof noteEntry === "string") {
        return {
          ...createDefaultNoteEntry(index),
          note: noteEntry,
        };
      }

      return normalizeNoteEntry(noteEntry, index);
    });
  }

  if (typeof notes === "string" && notes.trim()) {
    return [
      { ...createDefaultNoteEntry(0), note: notes },
      createDefaultNoteEntry(1),
      createDefaultNoteEntry(2),
    ];
  }

  return createEmptyNotes();
};

const SectionNotesManager = ({ notes, section, onSave }) => {
  const currentEstimate = useSelector((state) => state.estimates.currentEstimate);
  const { teamDefaults } = useSelector((state) => state.teamEstimateDefaults);
  const { boxMaterials, faceMaterials, drawerBoxMaterials } = useSelector(
    (state) => state.materials,
  );
  const finishTypes = useSelector((state) => state.finishes.finishes);
  const allCabinetStyles = useSelector((state) => state.cabinetStyles?.styles || []);
  const allCabinetTypes = useSelector((state) => state.cabinetTypes?.types || []);
  const hardware = useSelector((state) => state.hardware);
  const accessories = useSelector((state) => state.accessories);
  const lengths = useSelector((state) => state.lengths);
  const partsListAnchors = useSelector(
    (state) => state.partsListAnchors.itemsByPartsList,
  );
  const cabinetAnchors = useSelector((state) => state.cabinetAnchors.itemsByType);
  const globalServices = useSelector((state) => state.services.allServices);

  const cabinetStyles = useMemo(
    () => allCabinetStyles.filter((style) => style.is_active),
    [allCabinetStyles],
  );
  const cabinetTypes = useMemo(
    () => allCabinetTypes.filter((type) => type.is_active),
    [allCabinetTypes],
  );

  const resolvedNotes = notes ?? section?.notes;
  const [isEditing, setIsEditing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [formNotes, setFormNotes] = useState(() => normalizeNotes(resolvedNotes));
  const [savedNotes, setSavedNotes] = useState(() => normalizeNotes(resolvedNotes));

  useEffect(() => {
    const normalized = normalizeNotes(resolvedNotes);
    setSavedNotes(normalized);

    if (!isEditing) {
      setFormNotes(normalized);
    }
  }, [resolvedNotes, isEditing]);

  const {
    autoGeneratedNotesText,
    autoGeneratedIncludesText,
    autoGeneratedDoesNotIncludeText,
  } = useMemo(() => {
    if (!section || !currentEstimate) {
      return {
        autoGeneratedNotesText: "",
        autoGeneratedIncludesText: "",
        autoGeneratedDoesNotIncludeText: "",
      };
    }

    const catalogData = {
      boxMaterials,
      faceMaterials,
      drawerBoxMaterials,
      finishTypes,
      cabinetStyles,
      cabinetTypes,
      hardware,
      partsListAnchors,
      cabinetAnchors,
      globalServices,
      lengthsCatalog: lengths?.catalog,
      accessories,
      teamDefaults,
    };

    const { context, effectiveSection } = createSectionContext(
      section,
      currentEstimate,
      catalogData,
    );
    const calculations = getSectionCalculations(effectiveSection, context);

    const hasDoors =
      (calculations.faceCounts?.door || 0) +
        (calculations.faceCounts?.panel || 0) >
      0;
    const hasDrawerFronts =
      (calculations.faceCounts?.drawer_front || 0) +
        (calculations.faceCounts?.false_front || 0) >
      0;
    const hasDrawerBoxes =
      (calculations.drawerBoxCount || 0) + (calculations.rollOutCount || 0) > 0;

    const { additionalNotesText, includesText, doesNotIncludeText } = buildAdditionalSectionNotesText({
      effectiveSection,
      hasDoors,
      hasDrawerFronts,
      hasDrawerBoxes,
      faceMaterials,
      finishTypes,
      hardware: context?.hardware,
      lengthsCatalog: context?.lengthsCatalog,
    });
    return {
      autoGeneratedNotesText: additionalNotesText,
      autoGeneratedIncludesText: includesText,
      autoGeneratedDoesNotIncludeText: doesNotIncludeText,
    };
  }, [
    section,
    currentEstimate,
    boxMaterials,
    faceMaterials,
    drawerBoxMaterials,
    finishTypes,
    cabinetStyles,
    cabinetTypes,
    hardware,
    partsListAnchors,
    cabinetAnchors,
    globalServices,
    lengths,
    accessories,
    teamDefaults,
  ]);

  const hasChanges = useMemo(() => {
    return JSON.stringify(formNotes) !== JSON.stringify(savedNotes);
  }, [formNotes, savedNotes]);

  const handleChange = (index, value) => {
    setFormNotes((prev) => {
      const next = [...prev];
      next[index] = { ...next[index], note: value };
      return next;
    });
  };

  const handleOptionToggle = (noteIndex, optKey, optType, checked) => {
    setFormNotes((prev) => {
      const next = [...prev];
      const entry = next[noteIndex] || createDefaultNoteEntry(noteIndex);
      const prevOptions = entry.options || {};

      let newValue;
      if (optType === "text-boolean") {
        const currentVal = Array.isArray(prevOptions[optKey]) ? prevOptions[optKey] : [false, ""];
        newValue = [checked, currentVal[1]];
      } else {
        newValue = checked;
      }

      next[noteIndex] = {
        ...entry,
        options: { ...prevOptions, [optKey]: newValue },
      };
      return next;
    });
  };

  const handleOptionTextChange = (noteIndex, optKey, text) => {
    setFormNotes((prev) => {
      const next = [...prev];
      const entry = next[noteIndex] || createDefaultNoteEntry(noteIndex);
      const prevOptions = entry.options || {};
      const currentVal = Array.isArray(prevOptions[optKey]) ? prevOptions[optKey] : [false, ""];

      next[noteIndex] = {
        ...entry,
        options: { ...prevOptions, [optKey]: [currentVal[0], text] },
      };
      return next;
    });
  };

  const handleEdit = () => {
    setFormNotes(normalizeNotes(savedNotes));
    setIsEditing(true);
  };

  const handleCancel = () => {
    setFormNotes(normalizeNotes(savedNotes));
    setIsEditing(false);
  };

  const buildOptionsForSave = (entry, noteIndex) => {
    const saved = {};
    const raw = entry?.options || {};

    getOptionsForNoteIndex(noteIndex).forEach((opt) => {
      if (opt.type === "text-boolean") {
        const arr = Array.isArray(raw[opt.key]) ? raw[opt.key] : [false, ""];
        if (arr[0]) {
          saved[opt.key] = typeof arr[1] === "string" ? arr[1].trim() : "";
        }
      } else {
        if (raw[opt.key]) {
          saved[opt.key] = true;
        }
      }
    });

    return saved;
  };

  const handleSave = async () => {
    setIsSaving(true);

    const normalizedForSave = formNotes.map((entry, index) => ({
      note: entry.note.trim(),
      options: buildOptionsForSave(entry, index),
    }));
    const hasAnyValue = normalizedForSave.some(
      (entry) =>
        entry.note.length > 0 ||
        Object.keys(entry.options || {}).length > 0,
    );
    const payload = hasAnyValue ? normalizedForSave : null;
    const nextSavedNotes = normalizeNotes(payload);

    try {
      await onSave(payload);
      setSavedNotes(nextSavedNotes);
      setFormNotes(nextSavedNotes);
      setIsEditing(false);
    } catch {
      alert("Failed to save section notes. Please try again.");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="p-4 bg-white">
      <div className="flex items-center justify-between mb-4">
        <h4 className="text-sm font-medium text-slate-700">Section Notes</h4>
        {!isEditing ? (
          <button
            onClick={handleEdit}
            className="flex items-center gap-1 px-3 py-1.5 text-sm bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors"
          >
            <FiEdit2 size={14} />
            Edit
          </button>
        ) : (
          <div className="flex items-center gap-2">
            <button
              onClick={handleCancel}
              disabled={isSaving}
              className="flex items-center gap-1 px-3 py-1.5 text-sm bg-red-500 text-white rounded hover:bg-red-600 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
            >
              <FiX size={14} />
              Cancel
            </button>
            <button
              onClick={handleSave}
              disabled={isSaving || !hasChanges}
              className="flex items-center gap-1 px-3 py-1.5 text-sm bg-teal-600 text-white rounded hover:bg-teal-700 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
            >
              <FiSave size={14} />
              {isSaving ? "Saving..." : "Save"}
            </button>
          </div>
        )}
      </div>

      {(autoGeneratedNotesText || autoGeneratedIncludesText || autoGeneratedDoesNotIncludeText) && (
        <div className="mb-4 px-3 py-2 border border-slate-200 rounded-md bg-slate-50">
          <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 mb-1">
            Auto-generated
          </p>
          {autoGeneratedNotesText && (
            <p className="text-sm text-slate-700">{autoGeneratedNotesText}</p>
          )}
          {autoGeneratedIncludesText && (
            <p className="text-sm text-slate-700">Includes: {autoGeneratedIncludesText}</p>
          )}
          {autoGeneratedDoesNotIncludeText && (
            <p className="text-sm text-slate-700">Does Not Include: {autoGeneratedDoesNotIncludeText}</p>
          )}
        </div>
      )}

      <div className="grid grid-cols-1 items-start text-slate-700 px-1 gap-4">
        {["Notes", "Includes", "Does Not Include"].map((label, noteIndex) => {
          const noteOptions = getOptionsForNoteIndex(noteIndex);
          const placeholders = [
            "Any special notes...",
            "What's included...",
            "What's not included...",
          ];

          return (
            <div key={noteIndex}>
              <label
                htmlFor={`section-notes-${noteIndex}`}
                className="text-left text-sm font-bold flex items-center text-slate-700"
              >
                {label}
              </label>

              {noteOptions.length > 0 && (
                <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-2">
                  {noteOptions.map((opt) => {
                    const optionValue = formNotes[noteIndex]?.options?.[opt.key];

                    if (opt.type === "text-boolean") {
                      const checked = Array.isArray(optionValue) ? Boolean(optionValue[0]) : false;
                      const textVal = Array.isArray(optionValue) ? optionValue[1] || "" : "";

                      return (
                        <div key={opt.key} className="inline-flex items-center gap-2">
                          <label className="inline-flex items-center gap-2 text-sm text-slate-700">
                            <input
                              type="checkbox"
                              checked={checked}
                              onChange={(e) =>
                                handleOptionToggle(noteIndex, opt.key, opt.type, e.target.checked)
                              }
                              disabled={!isEditing}
                              className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500 disabled:opacity-60"
                            />
                            <span>{opt.label}</span>
                          </label>
                          <input
                            type="text"
                            value={textVal}
                            onChange={(e) =>
                              handleOptionTextChange(noteIndex, opt.key, e.target.value)
                            }
                            disabled={!isEditing || !checked}
                            className="w-8 rounded-md border border-slate-300 px-1 py-1 text-sm text-center focus:border-blue-500 focus:ring-1 focus:ring-blue-500 disabled:bg-slate-100 disabled:text-slate-500"
                            placeholder={opt.placeholder || ""}
                          />
                          {opt.suffix && (
                            <span className="text-sm text-slate-700">{opt.suffix}</span>
                          )}
                        </div>
                      );
                    }

                    return (
                      <label
                        key={opt.key}
                        className="inline-flex items-center gap-2 text-sm text-slate-700"
                      >
                        <input
                          type="checkbox"
                          checked={Boolean(optionValue)}
                          onChange={(e) =>
                            handleOptionToggle(noteIndex, opt.key, opt.type, e.target.checked)
                          }
                          disabled={!isEditing}
                          className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500 disabled:opacity-60"
                        />
                        <span>{opt.label}</span>
                      </label>
                    );
                  })}
                </div>
              )}

              <textarea
                id={`section-notes-${noteIndex}`}
                value={formNotes[noteIndex]?.note || ""}
                onChange={(e) => handleChange(noteIndex, e.target.value)}
                disabled={!isEditing}
                rows={3}
                className="mt-1 p-2 block w-full rounded-md border border-slate-300 text-sm focus:border-blue-500 focus:ring-1 focus:ring-blue-500 resize-y disabled:bg-slate-100 disabled:text-slate-500"
                placeholder={placeholders[noteIndex]}
              />
            </div>
          );
        })}
      </div>
    </div>
  );
};

SectionNotesManager.propTypes = {
  notes: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOfType([
        PropTypes.string,
        PropTypes.shape({
          note: PropTypes.string,
          options: PropTypes.object,
        }),
      ]),
    ),
    PropTypes.string,
    PropTypes.oneOf([null]),
  ]),
  section: PropTypes.object,
  onSave: PropTypes.func.isRequired,
};

export default SectionNotesManager;
