export const Actions = {
	jobs: {
		SAVE_JOBS: "SAVE_JOBS",
		UPDATE_JOB_START_DATE: "UPDATE_JOB_START_DATE",
		UPDATE_JOB_AND_ROOMS: "UPDATE_JOB_AND_ROOMS",
		INCREMENT_JOB_NUMBER: "INCREMENT_JOB_NUMBER",
	},
	builders: {
		ADD_BUILDER: "ADD_BUILDER",
		DELETE_BUILDER: "DELETE_BUILDER",
		UPDATE_BUILDER: "UPDATE_BUILDER",
	},
};

