export const accessories = {
  FETCH_ACCESSORIES_CATALOG_START: "FETCH_ACCESSORIES_CATALOG_START",
  FETCH_ACCESSORIES_CATALOG_SUCCESS: "FETCH_ACCESSORIES_CATALOG_SUCCESS",
  FETCH_ACCESSORIES_CATALOG_ERROR: "FETCH_ACCESSORIES_CATALOG_ERROR",

  SAVE_ACCESSORIES_CATALOG_START: "SAVE_ACCESSORIES_CATALOG_START",
  SAVE_ACCESSORIES_CATALOG_SUCCESS: "SAVE_ACCESSORIES_CATALOG_SUCCESS",
  SAVE_ACCESSORIES_CATALOG_ERROR: "SAVE_ACCESSORIES_CATALOG_ERROR",

  FETCH_ACCESSORY_TIME_ANCHORS_START: "FETCH_ACCESSORY_TIME_ANCHORS_START",
  FETCH_ACCESSORY_TIME_ANCHORS_SUCCESS: "FETCH_ACCESSORY_TIME_ANCHORS_SUCCESS",
  FETCH_ACCESSORY_TIME_ANCHORS_ERROR: "FETCH_ACCESSORY_TIME_ANCHORS_ERROR",

  SAVE_ACCESSORY_TIME_ANCHORS_START: "SAVE_ACCESSORY_TIME_ANCHORS_START",
  SAVE_ACCESSORY_TIME_ANCHORS_SUCCESS: "SAVE_ACCESSORY_TIME_ANCHORS_SUCCESS",
  SAVE_ACCESSORY_TIME_ANCHORS_ERROR: "SAVE_ACCESSORY_TIME_ANCHORS_ERROR",
};
