export const cabinetAnchors = {
  FETCH_CABINET_ANCHORS_START: 'FETCH_CABINET_ANCHORS_START',
  FETCH_CABINET_ANCHORS_SUCCESS: 'FETCH_CABINET_ANCHORS_SUCCESS',
  FETCH_CABINET_ANCHORS_ERROR: 'FETCH_CABINET_ANCHORS_ERROR',

  CREATE_CABINET_ANCHOR_START: 'CREATE_CABINET_ANCHOR_START',
  CREATE_CABINET_ANCHOR_SUCCESS: 'CREATE_CABINET_ANCHOR_SUCCESS',
  CREATE_CABINET_ANCHOR_ERROR: 'CREATE_CABINET_ANCHOR_ERROR',

  UPDATE_CABINET_ANCHOR_START: 'UPDATE_CABINET_ANCHOR_START',
  UPDATE_CABINET_ANCHOR_SUCCESS: 'UPDATE_CABINET_ANCHOR_SUCCESS',
  UPDATE_CABINET_ANCHOR_ERROR: 'UPDATE_CABINET_ANCHOR_ERROR',

  DELETE_CABINET_ANCHOR_START: 'DELETE_CABINET_ANCHOR_START',
  DELETE_CABINET_ANCHOR_SUCCESS: 'DELETE_CABINET_ANCHOR_SUCCESS',
  DELETE_CABINET_ANCHOR_ERROR: 'DELETE_CABINET_ANCHOR_ERROR',
};
