  export const cabinetTypes = {
    FETCH_CABINET_TYPES_START: "FETCH_CABINET_TYPES_START",
    FETCH_CABINET_TYPES_SUCCESS: "FETCH_CABINET_TYPES_SUCCESS",
    FETCH_CABINET_TYPES_ERROR: "FETCH_CABINET_TYPES_ERROR",
  
    ADD_CABINET_TYPE_START: "ADD_CABINET_TYPE_START",
    ADD_CABINET_TYPE_SUCCESS: "ADD_CABINET_TYPE_SUCCESS",
    ADD_CABINET_TYPE_ERROR: "ADD_CABINET_TYPE_ERROR",
  
    UPDATE_CABINET_TYPE_START: "UPDATE_CABINET_TYPE_START",
    UPDATE_CABINET_TYPE_SUCCESS: "UPDATE_CABINET_TYPE_SUCCESS",
    UPDATE_CABINET_TYPE_ERROR: "UPDATE_CABINET_TYPE_ERROR",
  }