export const cabinetAnchors = {
  FETCH_CABINET_ANCHORS_START: 'FETCH_CABINET_ANCHORS_START',
  FETCH_CABINET_ANCHORS_SUCCESS: 'FETCH_CABINET_ANCHORS_SUCCESS',
  FETCH_CABINET_ANCHORS_ERROR: 'FETCH_CABINET_ANCHORS_ERROR',

  // Generic action for the start and error of the save process
  UPDATE_CABINET_ANCHOR_START: 'UPDATE_CABINET_ANCHOR_START',
  UPDATE_CABINET_ANCHOR_ERROR: 'UPDATE_CABINET_ANCHOR_ERROR',
};
