export const cabinetStyles = {
  FETCH_TEAM_CABINET_STYLES_START: "FETCH_TEAM_CABINET_STYLES_START",
  FETCH_TEAM_CABINET_STYLES_SUCCESS: "FETCH_TEAM_CABINET_STYLES_SUCCESS",
  FETCH_TEAM_CABINET_STYLES_ERROR: "FETCH_TEAM_CABINET_STYLES_ERROR",

  ADD_TEAM_CABINET_STYLE_START: "ADD_TEAM_CABINET_STYLE_START",
  ADD_TEAM_CABINET_STYLE_SUCCESS: "ADD_TEAM_CABINET_STYLE_SUCCESS",
  ADD_TEAM_CABINET_STYLE_ERROR: "ADD_TEAM_CABINET_STYLE_ERROR",

  UPDATE_TEAM_CABINET_STYLES_START: "UPDATE_TEAM_CABINET_STYLES_START",
  UPDATE_TEAM_CABINET_STYLES_SUCCESS: "UPDATE_TEAM_CABINET_STYLES_SUCCESS",
  UPDATE_TEAM_CABINET_STYLES_ERROR: "UPDATE_TEAM_CABINET_STYLES_ERROR",
};
