export const finishes = {
  FETCH_FINISHES_START: "FETCH_FINISHES_START",
  FETCH_FINISHES_SUCCESS: "FETCH_FINISHES_SUCCESS",
  FETCH_FINISHES_ERROR: "FETCH_FINISHES_ERROR",

  SAVE_FINISHES_START: "SAVE_FINISHES_START",
  SAVE_FINISHES_SUCCESS: "SAVE_FINISHES_SUCCESS",
  SAVE_FINISHES_ERROR: "SAVE_FINISHES_ERROR",
};
