export const hardware = {
    FETCH_HARDWARE_START: "FETCH_HARDWARE_START",
    FETCH_HARDWARE_SUCCESS: "FETCH_HARDWARE_SUCCESS",
    FETCH_HARDWARE_ERROR: "FETCH_HARDWARE_ERROR",
  
    SAVE_HARDWARE_START: "SAVE_HARDWARE_START",
    SAVE_HARDWARE_SUCCESS: "SAVE_HARDWARE_SUCCESS",
    SAVE_HARDWARE_ERROR: "SAVE_HARDWARE_ERROR",
  
    FETCH_HINGES_SUCCESS: "FETCH_HINGES_SUCCESS",
    FETCH_PULLS_SUCCESS: "FETCH_PULLS_SUCCESS",
    FETCH_SLIDES_SUCCESS: "FETCH_SLIDES_SUCCESS",
  };
  