export const lengths = {
  FETCH_LENGTHS_CATALOG_START: "FETCH_LENGTHS_CATALOG_START",
  FETCH_LENGTHS_CATALOG_SUCCESS: "FETCH_LENGTHS_CATALOG_SUCCESS",
  FETCH_LENGTHS_CATALOG_ERROR: "FETCH_LENGTHS_CATALOG_ERROR",

  SAVE_LENGTHS_CATALOG_START: "SAVE_LENGTHS_CATALOG_START",
  SAVE_LENGTHS_CATALOG_SUCCESS: "SAVE_LENGTHS_CATALOG_SUCCESS",
  SAVE_LENGTHS_CATALOG_ERROR: "SAVE_LENGTHS_CATALOG_ERROR",

  FETCH_LENGTH_TIME_ANCHORS_START: "FETCH_LENGTH_TIME_ANCHORS_START",
  FETCH_LENGTH_TIME_ANCHORS_SUCCESS: "FETCH_LENGTH_TIME_ANCHORS_SUCCESS",
  FETCH_LENGTH_TIME_ANCHORS_ERROR: "FETCH_LENGTH_TIME_ANCHORS_ERROR",

  SAVE_LENGTH_TIME_ANCHORS_START: "SAVE_LENGTH_TIME_ANCHORS_START",
  SAVE_LENGTH_TIME_ANCHORS_SUCCESS: "SAVE_LENGTH_TIME_ANCHORS_SUCCESS",
  SAVE_LENGTH_TIME_ANCHORS_ERROR: "SAVE_LENGTH_TIME_ANCHORS_ERROR",
};
