export const materials = {
  FETCH_MATERIALS_START: "FETCH_MATERIALS_START",
  FETCH_MATERIALS_SUCCESS: "FETCH_MATERIALS_SUCCESS",
  FETCH_MATERIALS_ERROR: "FETCH_MATERIALS_ERROR",

  ADD_MATERIAL_START: "ADD_MATERIAL_START",
  ADD_MATERIAL_SUCCESS: "ADD_MATERIAL_SUCCESS",
  ADD_MATERIAL_ERROR: "ADD_MATERIAL_ERROR",

  UPDATE_MATERIAL_START: "UPDATE_MATERIAL_START",
  UPDATE_MATERIAL_SUCCESS: "UPDATE_MATERIAL_SUCCESS",
  UPDATE_MATERIAL_ERROR: "UPDATE_MATERIAL_ERROR",

  DELETE_MATERIAL_START: "DELETE_MATERIAL_START",
  DELETE_MATERIAL_SUCCESS: "DELETE_MATERIAL_SUCCESS",
  DELETE_MATERIAL_ERROR: "DELETE_MATERIAL_ERROR",

  FETCH_SHEET_GOODS_SUCCESS: "FETCH_SHEET_GOODS_SUCCESS",
  FETCH_DRAWER_BOX_MATERIALS_SUCCESS: "FETCH_DRAWER_BOX_MATERIALS_SUCCESS",
};
