export const materials = {
  FETCH_MATERIALS_START: "FETCH_MATERIALS_START",
  FETCH_MATERIALS_SUCCESS: "FETCH_MATERIALS_SUCCESS",
  FETCH_MATERIALS_ERROR: "FETCH_MATERIALS_ERROR",

  SAVE_MATERIALS_START: "SAVE_MATERIALS_START",
  SAVE_MATERIALS_SUCCESS: "SAVE_MATERIALS_SUCCESS",
  SAVE_MATERIALS_ERROR: "SAVE_MATERIALS_ERROR",

  FETCH_SHEET_GOODS_SUCCESS: "FETCH_SHEET_GOODS_SUCCESS",
  FETCH_DRAWER_BOX_MATERIALS_SUCCESS: "FETCH_DRAWER_BOX_MATERIALS_SUCCESS",
};
