export const partsListAnchors = {
  FETCH_PARTS_LIST_ANCHORS_START: 'FETCH_PARTS_LIST_ANCHORS_START',
  FETCH_PARTS_LIST_ANCHORS_SUCCESS: 'FETCH_PARTS_LIST_ANCHORS_SUCCESS',
  FETCH_PARTS_LIST_ANCHORS_ERROR: 'FETCH_PARTS_LIST_ANCHORS_ERROR',

  // Generic action for the start and error of the save process
  UPDATE_PARTS_LIST_ANCHOR_START: 'UPDATE_PARTS_LIST_ANCHOR_START',
  UPDATE_PARTS_LIST_ANCHOR_ERROR: 'UPDATE_PARTS_LIST_ANCHOR_ERROR',
};
