export const teamEstimateDefaults = {
  FETCH_TEAM_DEFAULTS_START: "FETCH_TEAM_DEFAULTS_START",
  FETCH_TEAM_DEFAULTS_SUCCESS: "FETCH_TEAM_DEFAULTS_SUCCESS",
  FETCH_TEAM_DEFAULTS_ERROR: "FETCH_TEAM_DEFAULTS_ERROR",

  UPDATE_TEAM_DEFAULTS_START: "UPDATE_TEAM_DEFAULTS_START",
  UPDATE_TEAM_DEFAULTS_SUCCESS: "UPDATE_TEAM_DEFAULTS_SUCCESS",
  UPDATE_TEAM_DEFAULTS_ERROR: "UPDATE_TEAM_DEFAULTS_ERROR",
};
